/**
 * adaicons
 */

// Import the CSS
if (typeof document !== 'undefined') {
  const link = document.createElement('link');
  link.rel = 'stylesheet';
  link.href = './style.css';
  document.head.appendChild(link);
}

module.exports = {
  icons: [
    'arrow-down',
    'arrow-left',
    'arrow-right',
    'arrow-up',
    'bar-chart',
    'bar-chart-filled',
    'bin',
    'bookmark',
    'bookmark-filled',
    'chevron-down',
    'chevron-left',
    'chevron-right',
    'chevron-up',
    'cog',
    'cog-filled',
    'cog-smooth',
    'cog-smooth-filled',
    'cog-sparkle',
    'cog-sparkle-filled',
    'copy',
    'copy-filled',
    'csv',
    'divide',
    'filter',
    'filter-filled',
    'grouped-bar-chart',
    'grouped-bar-chart-filled',
    'help',
    'history',
    'i',
    'line-chart',
    'link',
    'mic',
    'mic-filled',
    'new-conversation',
    'number',
    'percent',
    'pie-chart',
    'pie-chart-filled',
    'plus',
    'profile',
    'profile-filled',
    'share',
    'sparkle',
    'sparkle-filled',
    'speech-sparkle',
    'speech-sparkle-filled',
    'stack',
    'stack-filled',
    'table',
    'thumb-down',
    'thumb-down-filled',
    'thump-up',
    'thump-up-filled',
    'tick',
    'triangle-down',
    'triangle-left',
    'triangle-right',
    'triangle-up',
    'x'
  ],

  
  unicodes: {
    'arrow-down': 'e939',
    'arrow-left': 'e938',
    'arrow-right': 'e900',
    'arrow-up': 'e93a',
    'bar-chart': 'e901',
    'bar-chart-filled': 'e902',
    'bin': 'e903',
    'bookmark': 'e904',
    'bookmark-filled': 'e905',
    'chevron-down': 'e92f',
    'chevron-left': 'e930',
    'chevron-right': 'e931',
    'chevron-up': 'e932',
    'cog': 'e906',
    'cog-filled': 'e907',
    'cog-smooth': 'e908',
    'cog-smooth-filled': 'e909',
    'cog-sparkle': 'e90a',
    'cog-sparkle-filled': 'e90b',
    'copy': 'e90c',
    'copy-filled': 'e90d',
    'csv': 'e92d',
    'divide': 'e913',
    'filter': 'e90e',
    'filter-filled': 'e90f',
    'grouped-bar-chart': 'e910',
    'grouped-bar-chart-filled': 'e911',
    'help': 'e912',
    'history': 'e92e',
    'i': 'e933',
    'line-chart': 'e914',
    'link': 'e93b',
    'mic': 'e915',
    'mic-filled': 'e916',
    'new-conversation': 'e917',
    'number': 'e918',
    'percent': 'e919',
    'pie-chart': 'e91a',
    'pie-chart-filled': 'e91b',
    'plus': 'e91c',
    'profile': 'e91d',
    'profile-filled': 'e91e',
    'share': 'e91f',
    'sparkle': 'e920',
    'sparkle-filled': 'e921',
    'speech-sparkle': 'e922',
    'speech-sparkle-filled': 'e923',
    'stack': 'e924',
    'stack-filled': 'e925',
    'table': 'e926',
    'thumb-down': 'e927',
    'thumb-down-filled': 'e928',
    'thump-up': 'e929',
    'thump-up-filled': 'e92a',
    'tick': 'e92b',
    'triangle-down': 'e934',
    'triangle-left': 'e935',
    'triangle-right': 'e936',
    'triangle-up': 'e937',
    'x': 'e92c'
  }
};